"""init

Revision ID: 679f288c7b61
Revises: 
Create Date: 2026-06-29 20:28:56.667352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679f288c7b61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sic_code', sa.String(length=4), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('gics_sector', sa.String(length=100), nullable=True),
    sa.Column('gics_industry_group', sa.String(length=100), nullable=True),
    sa.Column('gics_industry', sa.String(length=100), nullable=True),
    sa.Column('gics_sub_industry', sa.String(length=100), nullable=True),
    sa.Column('is_snp500', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('concept', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source_filing', sa.String(length=255), nullable=True),
    sa.Column('statement_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'fiscal_period', 'concept', name='uq_financial_fact')
    )
    op.create_index(op.f('ix_financial_facts_company_id'), 'financial_facts', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_facts_concept'), 'financial_facts', ['concept'], unique=False)
    op.create_index(op.f('ix_financial_facts_ticker'), 'financial_facts', ['ticker'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('insider_name', sa.String(length=255), nullable=True),
    sa.Column('insider_title', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_transactions_company_id'), 'insider_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_insider_transactions_ticker'), 'insider_transactions', ['ticker'], unique=False)
    op.create_table('institutional_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('reporting_manager', sa.String(length=255), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_holdings_company_id'), 'institutional_holdings', ['company_id'], unique=False)
    op.create_index(op.f('ix_institutional_holdings_ticker'), 'institutional_holdings', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutional_holdings_ticker'), table_name='institutional_holdings')
    op.drop_index(op.f('ix_institutional_holdings_company_id'), table_name='institutional_holdings')
    op.drop_table('institutional_holdings')
    op.drop_index(op.f('ix_insider_transactions_ticker'), table_name='insider_transactions')
    op.drop_index(op.f('ix_insider_transactions_company_id'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_financial_facts_ticker'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_concept'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_company_id'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
