"""add_company_fk

Revision ID: d8e8c9528f73
Revises: 679f288c7b61
Create Date: 2026-06-29 21:01:06.787531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e8c9528f73'
down_revision: Union[str, Sequence[str], None] = '679f288c7b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_financial_facts_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('insider_transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_insider_transactions_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('institutional_holdings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_institutional_holdings_company_id', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutional_holdings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_institutional_holdings_company_id', type_='foreignkey')

    with op.batch_alter_table('insider_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insider_transactions_company_id', type_='foreignkey')

    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_financial_facts_company_id', type_='foreignkey')
    # ### end Alembic commands ###
